### PR TITLE
This is the new pull request for the 6 new replaced files

### PR DESCRIPTION
**Pull request by mehdigithub1**

### CODE REVIEW

**Comment by mehdigithub1** [comment]
Please ignore the verifications error, as if those are because of the bent loss of the spiral paperclips.

**Comment by mehdigithub1** [comment]
So, please accept them to be merged in the final layout. Thanks!

**Comment by mehdigithub1** [comment]
I have added 4 more files (EBeam_Mehdi_paperclips_5, EBeam_Mehdi_paperclips_5_2nd, EBeam_Mehdi_paperclips_6 & EBeam_Mehdi_paperclips_6_2nd, thu I can not see them to be checked. Those are in my submission folder but I am not able to make another pull request for them.

**Comment by lukasc-ubc** [comment]
image

**Comment by lukasc-ubc** [comment]
I think two files (or more) have this issue.

**Comment by mehdigithub1** [comment]
Thank you for the comment. I corrected the error. It was in two files (EBeam_Mehdi_paperclips_5 and EBeam_Mehdi_paperclips_5_2nd). I will delete them and upload them again.

**Comment by lukasc-ubc** [comment]
getting closer...

Running SiEPIC-Tools automated verification for file submissions/EBeam_Mehdi_paperclips_3.gds
Error: layout does not have 1 top cell. It has 2.

**Pull request merged**
