### PR TITLE
Pull request- Paperclips designs

### PR DESCRIPTION
**Pull request by mehdigithub1**
…s each (6 total). It is needed to find the error bar according to the three times of the same devices.

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
please remove spaces from your filenames.

thank you

**Comment by lukasc-ubc** [comment]
please remove spaces from your filenames.

thank you

@lukasc-ubc

**Comment by mehdigithub1** [comment]
Sure, I will do it. I actually wanted to submit another request, a
corrected design with a corrected filenames as well.

**Comment by lukasc-ubc** [comment]
Merging.  But note that there are 0 files changed here.  So you may need to resubmit via a new PR.

**Pull request merged**
