### PR TITLE
Hady moussa patch 1

### PR DESCRIPTION
**Pull request by HadyMoussa**

### CODE REVIEW

**Comment by HadyMoussa** [comment]
attempt

**Comment by HadyMoussa** [comment]
This is one more attempt

**Comment by lukasc-ubc** [comment]
also two identical files? can you please clean up?

**Comment by HadyMoussa** [comment]
I have deleted the extra file... but I have another submission, was trying to upload the design.. can you choose any of them and ask me to delete the other?

**Pull request closed without merging**
