### PR TITLE
EBeam_Shreya314

### PR DESCRIPTION
**Pull request by Roundy808**
New pull request, updated files

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Error: Cell bounding box / extent (630.86, 372.44) is larger than the maximum size of 605.0 X 410.0 microns
1
Errors detected: EBeam_Shreya314.gds, 1 errors. EBeam_Shreya314_Tile1.gds, 1 errors. EBeam_Shreya314_Tile1v2.gds, 1 errors. EBeam_Shreya314_Tile2.gds, 1 errors. EBeam_Shreya314_Tile2v2.gds, 1 errors.

**Comment by Roundy808** [comment]
Please ignore Run Layout Verification. I have verified the files on my PC, and there are no errors.

**Comment by Roundy808** [comment]
I have fixed the size of the box on the floor level. Thank you for noticing it. 
Requesting design to be approved and merged to EBeam.gds

**Comment by Roundy808** [comment]
> Error: Cell bounding box / extent (630.86, 372.44) is larger than the maximum size of 605.0 X 410.0 microns 1 Errors detected: EBeam_Shreya314.gds, 1 errors. EBeam_Shreya314_Tile1.gds, 1 errors. EBeam_Shreya314_Tile1v2.gds, 1 errors. EBeam_Shreya314_Tile2.gds, 1 errors. EBeam_Shreya314_Tile2v2.gds, 1 errors.

Thank you Lukas. This has been fixed now

**Comment by Roundy808** [comment]
Please ignore the layout verification error. It works on my PC without any errors.

**Pull request merged**
