### PR TITLE
Layout Submission - Atilla

### PR DESCRIPTION
**Pull request by Tikila93**
Here is my Layout

### CODE REVIEW

**Comment by Tikila93** [comment]
I submitted again, because on idx I forgot to answer the Layout Submission question ([Course]
[Layout for Fabrication]
[Draft Layout Submission]) and I was hopping that I can submit. Moreover, I named the file wrong. Can you please help me to solve the problem ? 
Best, Atilla

**Comment by omidesml** [comment]
Thi is just loop backs. Will you be updating the design?

**Comment by Tikila93** [comment]
No, I did not update the design. I have one error with the file name that I fixed.

**Comment by omidesml** [comment]
Do you want to submit all loopbacks? 
image

**Comment by Tikila93** [comment]
Yes, I will provide all loopbacks. That's okay. I thought I'd keep it simple. Apologies for my late reply; I am currently on a business trip.

Best, Atilla

**Pull request merged**
