### PR TITLE
This is my designA pull request

### PR DESCRIPTION
**Pull request by HARproject2020**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Error: Shapes outside component: Shapes for device layers need to be inside a component. At minimum, they must be inside a cell and inside a DevRec shape. Read more about requirements for components: https://github.com/SiEPIC/SiEPIC-Tools/wiki/Component-and-PCell-Layout
Error: Shapes outside component: Shapes for device layers need to be inside a component. At minimum, they must be inside a cell and inside a DevRec shape. Read more about requirements for components: https://github.com/SiEPIC/SiEPIC-Tools/wiki/Component-and-PCell-Layout
Error: Disconnected pin: Disconnected pin
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Disconnected pin: Disconnected pin
Error: opt_in label: missing: Automated test opt_in labels are required for measurements on the Text layer. 

Details on the format for the opt_in labels can be found at https://github.com/lukasc-ubc/SiEPIC-Tools/wiki/SiEPIC-Tools-Menu-descriptions#connectivity-layout-check
 * Previous label: ('SiEPIC-Tools verification: 7 errors\n2024-10-02 11:24:[38](https://github.com/SiEPIC/openEBL-2024-10/actions/runs/11147230339/job/30981063368?pr=61#step:12:39)\nSiEPIC-Tools v0.4.5\ntechnology: EBeam\nwin32\nPython: 3.8.9 (default, Apr 13 2021, 15:54:59)  [GCC 10.2.0 64 bit (AMD64)], C:\\Users\\smahmo44\\AppData\\Roaming\\KLayout\\lib\\python3.8\nKLayout 0.28.12',r0 1086318,-6442[41](https://github.com/SiEPIC/openEBL-2024-10/actions/runs/11147230339/job/30981063368?pr=61#step:12:42)) s=100
KLayout SiEPIC-Tools version 0.5.12
13
Errors detected: EBeam_Shahab_A.gds, 12 errors. EBeam_Shahab_B.gds, 17 errors. EBeam_Shahab_C.gds, 9 errors. EBeam_Shahab_D.gds, 12 errors. EBeam_Shahab_E.gds, 13 errors. EBeam_Shahab_F.gds, 13 errors.

**Comment by omidesml** [comment]
There are lots of layout errors. Would you please clean and update the pull request? Don't leave waveguides open and stranded. Use termination.

**Comment by lukasc-ubc** [comment]
6 layout errors detected.  
Please review errors using the 'Marker Database Browser'.
Error: Shapes outside component: Shapes for device layers need to be inside a component. At minimum, they must be inside a cell and inside a DevRec shape. Read more about requirements for components: https://github.com/SiEPIC/SiEPIC-Tools/wiki/Component-and-PCell-Layout
Error: Shapes outside component: Shapes for device layers need to be inside a component. At minimum, they must be inside a cell and inside a DevRec shape. Read more about requirements for components: https://github.com/SiEPIC/SiEPIC-Tools/wiki/Component-and-PCell-Layout
Error: opt_in label: missing: Automated test opt_in labels are required for measurements on the Text layer. 

Details on the format for the opt_in labels can be found at https://github.com/lukasc-ubc/SiEPIC-Tools/wiki/SiEPIC-Tools-Menu-descriptions#connectivity-layout-check
Error: opt_in label: missing: Automated test opt_in labels are required for measurements on the Text layer. 

Details on the format for the opt_in labels can be found at https://github.com/lukasc-ubc/SiEPIC-Tools/wiki/SiEPIC-Tools-Menu-descriptions#connectivity-layout-check
Error: opt_in label: missing: Automated test opt_in labels are required for measurements on the Text layer. 

Details on the format for the opt_in labels can be found at https://github.com/lukasc-ubc/SiEPIC-Tools/wiki/SiEPIC-Tools-Menu-descriptions#connectivity-layout-check
Error: opt_in label: missing: Automated test opt_in labels are required for measurements on the Text layer. 

Details on the format for the opt_in labels can be found at https://github.com/lukasc-ubc/SiEPIC-Tools/wiki/SiEPIC-Tools-Menu-descriptions#connectivity-layout-check
 * Previous label: ('SiEPIC-Tools verification: 6 errors\n2024-10-03 02:13:15\nSiEPIC-Tools v0.4.5\ntechnology: EBeam\nwin32\nPython: 3.8.9 (default, Apr 13 2021, 15:54:59)  [GCC 10.2.0 64 bit (AMD64)], C:\\Users\\smahmo44\\AppData\\Roaming\\KLayout\\lib\\python3.8\nKLayout 0.28.12',r0 1086[31](https://github.com/SiEPIC/openEBL-2024-10/actions/runs/11166462753/job/31040660694?pr=61#step:12:32)8,-644241) s=100
KLayout SiEPIC-Tools version 0.5.12
6
Errors detected: EBeam_Shahab_A.gds, 5 errors. EBeam_Shahab_B.gds, 7 errors. EBeam_Shahab_C.gds, 5 errors. EBeam_Shahab_D.gds, 8 errors. EBeam_Shahab_E.gds, 1 errors. EBeam_Shahab_F.gds, 6 errors.

**Comment by HARproject2020** [comment]
Updated versions without error

**Pull request closed without merging**
