### PR TITLE
my design

### PR DESCRIPTION
**Pull request by dtarquimea**

### CODE REVIEW

**Comment by omidesml** [comment]
You are uploading one file under the root directory and one under the submission. Would you please update your request? Only into submission 
image

**Comment by dtarquimea** [comment]
hi @omidesml ! sorry, I'm quite lost with all of this... I think now it must be okay...

**Comment by lukasc-ubc** [comment]
75 layout errors detected.  
Please review errors using the 'Marker Database Browser'.
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Grating coupler orientation: The grating coupler is not oriented (rotated) the correct way for automated testing.
Error: Disconnected pin: Disconnected pin
Error: Grating coupler orientation: The grating coupler is not oriented (rotated) the correct way for automated testing.
Error: Disconnected pin: Disconnected pin
Error: Grating coupler orientation: The grating coupler is not oriented (rotated) the correct way for automated testing.
Error: Disconnected pin: Disconnected pin
Error: Grating coupler orientation: The grating coupler is not oriented (rotated) the correct way for automated testing.
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: too far away: Automated test opt_in labels must be placed at the tip of the grating coupler, namely near the (0,0) point of the cell.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
KLayout SiEPIC-Tools version 0.5.12
[75](https://github.com/SiEPIC/openEBL-2024-10/actions/runs/11159924801/job/31020159839?pr=73#step:12:76)
Errors detected: EBeam_dianamesquita.oas, 75 errors. EBeam_dianamesquita.oas, 75 errors.

**Comment by dtarquimea** [comment]
Hi!! When I run DRC I have no errors but then on the run layout verification I have several errors related to diconected pins, can you please help? thank you

**Comment by lukasc-ubc** [comment]
34 layout errors detected.  
Please review errors using the 'Marker Database Browser'.
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: Disconnected pin: Disconnected pin
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: opt_in label: missing: Automated test opt_in labels are required for measurements on the Text layer.

**Comment by dtarquimea** [comment]
why does my pull request says it has a bug if everything is alright???

**Comment by dtarquimea** [comment]
@omidesml @lukasc-ubc

**Pull request merged**
