### PR TITLE
My design (MathieuG38 on Edx)

### PR DESCRIPTION
**Pull request by Matman42**

### CODE REVIEW

**Comment by omidesml** [comment]
Would you please delete the laser and detectors from the layout. 
There is a problem with labels. make sure they are unique 
Clean the layout and update the pull request

**Comment by Matman42** [comment]
Hi, I removed the lasers and detectors and all labels seem unique

**Comment by lukasc-ubc** [comment]
- Found overlapping components: ebeam_wg_integral_1550, ebeam_wg_integral_1550
 - Found overlapping components: ebeam_wg_integral_1550, ebeam_wg_integral_1550
 - Found overlapping components: ebeam_gc_te1550, ebeam_gc_te1550
 - Found overlapping components: ebeam_y_1550, ebeam_y_1550
 - Found overlapping components: ebeam_gc_te1550, ebeam_gc_te1550
 - Found overlapping components: ebeam_gc_te1550, ebeam_gc_te1550
 - Found overlapping components: ebeam_bdc_te1550, ebeam_bdc_te1550
 - Found overlapping components: ebeam_wg_integral_1550, ebeam_wg_integral_1550
 - Found overlapping components: ebeam_wg_integral_1550, ebeam_wg_integral_1550
 - Found overlapping components: ebeam_wg_integral_1550, ebeam_wg_strip_1550
 - Found overlapping components: ebeam_wg_integral_1550, ebeam_wg_strip_1550
21 layout errors detected.  
Please review errors using the 'Marker Database Browser'.
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: Overlapping component: Overlapping components (defined as overlapping DevRec layers; touching is ok)
Error: opt_in label: same: Automated test opt_in labels should be unique.
Error: Fibre array configuration: Circuit must be connected such that there is at most 1 Grating Coupler(s)  above  the opt_in label (laser injection port) and at most 2 Grating Coupler(s)  below  the opt_in label. 
Grating couplers must be on a 127.0 micron pitch, vertically arranged.
Error: Fibre array configuration: Circuit must be connected such that there is at most 1 Grating Coupler(s)  above  the opt_in label (laser injection port) and at most 2 Grating Coupler(s)  below  the opt_in label. 
Grating couplers must be on a 127.0 micron pitch, vertically arranged.
Error: Fibre array configuration: Circuit must be connected such that there is at most 1 Grating Coupler(s)  above  the opt_in label (laser injection port) and at most 2 Grating Coupler(s)  below  the opt_in label. 
Grating couplers must be on a 127.0 micron pitch, vertically arranged.
Error: Fibre array configuration: Circuit must be connected such that there is at most 1 Grating Coupler(s)  above  the opt_in label (laser injection port) and at most 2 Grating Coupler(s)  below  the opt_in label. 
Grating couplers must be on a 127.0 micron pitch, vertically arranged.
 * Previous label: ('SiEPIC-Tools verification: 34 errors\n2024-10-01 15:16:44\nSiEPIC-Tools v0.5.11\ntechnology: EBeam\nwin[32](https://github.com/SiEPIC/openEBL-2024-10/actions/runs/11166462753/job/31040660694?pr=61#step:12:33)\nPython: 3.11.6 (main, Oct  3 2023, 09:12:56)  [GCC 13.2.0 64 bit (AMD64)], C:\\Users\\skywa\\AppData\\Roaming\\KLayout\\pymod\n[\'0\', \'29\', \'6\']',r0 -142920,-119250) s=100
 * Previous label: ('SiEPIC-Tools verification: 6 errors\n2024-10-01 15:20:49\nSiEPIC-Tools v0.5.11\ntechnology: EBeam\nwin32\nPython: 3.11.6 (main, Oct  3 2023, 09:12:56)  [GCC 13.2.0 64 bit (AMD64)], C:\\Users\\skywa\\AppData\\Roaming\\KLayout\\pymod\n[\'0\', \'29\', \'6\']',r0 0,0) s=100
 * Previous label: ('SiEPIC-Tools verification: 6 errors\n2024-10-01 15:28:08\nSiEPIC-Tools v0.5.11\ntechnology: EBeam\nwin32\nPython: 3.11.6 (main, Oct  3 2023, 09:12:56)  [GCC 13.2.0 64 bit (AMD64)], C:\\Users\\skywa\\AppData\\Roaming\\KLayout\\pymod\n[\'0\', \'29\', \'6\']',r0 0,0) s=100
KLayout SiEPIC-Tools version 0.5.12
21
Errors detected: EBeam_MathieuG[38](https://github.com/SiEPIC/openEBL-2024-10/actions/runs/11166462753/job/31040660694?pr=61#step:12:39)_A.gds, 21 errors.

**Comment by Matman42** [comment]
I did a last minute change to replace the spiral with the spiral paperclip to lift the remaining errors.

**Pull request merged**
