### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SalehhhQ**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Error: Cell bounding box / extent (1181.81, 741.23) is larger than the maximum size of 605.0 X 410.0 microns

**Comment by SalehhhQ** [comment]
Thanks for the feedback, I have double cheeked the floorplan box, its
dimensions are 605x410, I'm not sure where exactly is the error.

**Comment by SalehhhQ** [comment]
Hi @omidesml, I'm getting:
Error: Cell bounding box / extent (1181.81, 741.23) is larger than the maximum size of 605.0 X 410.0 microns
While I'm sure that the bounding box is at 605x410, how can i fix this?
thanks

**Comment by omidesml** [comment]
It's not. I selected the floor plan tille and then set the right coordinates 
image

See how much your design is bigger: 
image

**Comment by lukasc-ubc** [comment]
@SalehhhQ 

We are now past the deadline.  

Our next submission will be in February 2025.  
The repository will be set up soon: https://github.com/SiEPIC/openEBL-2025-02

You may fix your design and submit next time.

thank you
Lukas

**Pull request closed without merging**
