### PR TITLE
Trying to upload design using python script with GDS Factory

### PR DESCRIPTION
**Pull request by lbelangers**
As discussed in the Q&A, this is the design I'm having issues with (missing pins). I am unsure how the GitHub actions for running python files works, as it's not finding my python file.

### CODE REVIEW

**Comment by lbelangers** [comment]
It seems that the Python interpreter is missing dependencies.

```python
Traceback (most recent call last):
  File "/home/runner/work/openEBL-2024-10/openEBL-2024-10/submissions/KLayout Python/EBeam_lbelangers2.py", line 1, in <module>
    import gdsfactory as gf
ModuleNotFoundError: No module named 'gdsfactory'
```

**Comment by lukasc-ubc** [comment]
Hello @lbelangers 

The design you submitted has problems with the grating couplers.  You used a cell ("gc_te1550") that doesn't exist in the EBeam library.  We replace all the grating couplers.  And unfortunately your GC is also rotated relative to the ones in the library, so even if I replace it, I get an incorrect circuit.

image

Could you please fix your layout to use the "GC_TE_1550_8degOxide_BB" cell?  This is the one that we replace it with.

Otherwise, we can fabricate your design using the GC layout you provided, but it looks like it is a design for -31 degrees, whereas we only test the chip with +8º couplers.

**Comment by lukasc-ubc** [comment]
@lbelangers your gdsfactory code isn't compiling for some reason: https://github.com/SiEPIC/openEBL-2024-10/actions/runs/11321672596/job/31481081599?pr=172

**Comment by lbelangers** [comment]
H

> Hello @lbelangers
> 
> The design you submitted has problems with the grating couplers. You used a cell ("gc_te1550") that doesn't exist in the EBeam library. We replace all the grating couplers. And unfortunately your GC is also rotated relative to the ones in the library, so even if I replace it, I get an incorrect circuit.
> 
> image
> Could you please fix your layout to use the "GC_TE_1550_8degOxide_BB" cell? This is the one that we replace it with.
> 
> Otherwise, we can fabricate your design using the GC layout you provided, but it looks like it is a design for -31 degrees, whereas we only test the chip with +8º couplers.

Hi,

I can't seem to find GC_TE_1550_8degOxide_BB in the ubcpdk. Do I need to manually import the .gds to add it to my design. 
About the code not compiling, the error seem to be raised inside the gds factory import. I tried locally to run the code with the specific python and gds factory versions, but am not able to reproduce.

**Comment by lukasc-ubc** [comment]
Indeed, gdsfactory's PDK is out of date, and the GC cells need to be updated / imported from the main PDK.

**Comment by lukasc-ubc** [comment]
We are now past the deadline.

Our next submission will be in February 2025.
The repository will be set up soon: https://github.com/SiEPIC/openEBL-2025-02

You may fix your design and submit next time.

thank you
Lukas

**Comment by lbelangers** [comment]
If I understand correctly, my submission will still be fabricated as is (it's currently on the latest artifact), but will have greater insertion loss because the coupling angle is not the same?

**Comment by lukasc-ubc** [comment]
I replaced the GC manually. With a 40 degree angle difference, I don’t think it would work well at all. Lukas ChrostowskiProfessor, Electrical and Computer EngineeringUniversity of British ColumbiaQuantum Matter InstituteMember, College of the Royal Society of Canadahttp://siepic.ca Silicon Photonicshttp://quantum-bc.ca Quantum Computing CREATE programhttps://qmi.ubc.ca/about/directory/lukas-chrostowskiOn Oct 15, 2024, at 08:25, Louis Bélanger Sansoucy ***@***.***> wrote:﻿
If I understand correctly, my submission will still be fabricated as is (it's currently on the latest artifact), but will have greater insertion loss because the coupling angle is not the same?

**Pull request closed without merging**
