### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Jamesddin**

### CODE REVIEW

**Comment by Jamesddin** [comment]
I deleted the laser and detectors

**Comment by omidesml** [comment]
Layouts seem identical except for one of them that has lasers. Please delete the lasers and resubmit

**Comment by omidesml** [comment]
But you are still pulling two files. Keep the file's name the same.
image

**Comment by Jamesddin** [comment]
I think the file "JinWonYoo2" makes an error now. Could you please delete it?

**Pull request merged**
