### PR TITLE
My Layout

### PR DESCRIPTION
**Pull request by mghazialsharif**
Mohammad Ghazialsharif

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Hello,

It looks like you have a lot of duplicate files.  How many unique designs are you submitting?  one or two?

Can you please clean it up, to remove the extras?  Unless it is intentional? 

thank you

**Comment by mghazialsharif** [comment]
Dear Professor Chrostowski,

I have investigated the issues, but my layout is still not passing the tests. Since I do not have access to delete the failed layouts, could you please assist in deleting them?

Additionally, the last error message I received is unclear, and I'm not sure how to resolve it. Could you advise on how I can get help to fix this issue?

Thank you for your assistance.

Best regards,
Mohammad Ghazialsharif

**Comment by lukasc-ubc** [comment]
The way fix it is remove them on either GitHub web page, or on your local computer.  It should update the PR.

If you can't do it, then let me know: Which file do you want to keep, of the 9 that you uploaded?

**Comment by mghazialsharif** [comment]
Thank you but I couldn't delete them so please keep"Ebeam_Mghazialsharif_MZIv1.oas" and delete the rest.

Thank you very much

**Comment by omidesml** [comment]
I am closing this pull request. Please resubmit the intended file again. Thanks!

**Comment by mghazialsharif** [comment]
I can’t creat new pull request

**Pull request closed without merging**
