### PR TITLE
Version 1 of my silicon photonics circuit

### PR DESCRIPTION
**Pull request by IE99**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Error: Cell bounding box / extent (643.82, 410.0) is larger than the maximum size of 605.0 X 410.0 microns

**Comment by lukasc-ubc** [comment]
Also three Verification errors. can you please fix?

**Comment by omidesml** [comment]
Terminate the unused ports and update the pull request.

**Comment by IE99** [comment]
Hello, I have made the fixes to my branch. It should be error free now

**Pull request merged**
